# Generated by Django 5.0.1 on 2024-01-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='timestamp',
        ),
    ]
